spring:
  application:
    name: home-repair
  datasource:
#    url: jdbc:postgresql://localhost:5433/homerepair
#    username: myuser
#    password: mypassword
#    driver-class-name: org.postgresql.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8081

gg:
  jte:
    templateLocation: src/main/jte
    developmentMode: true

logging:
  level:
    gg.jte: DEBUG
    org.springframework.web: DEBUG
